### PR TITLE
Provide req/res, improve search for uuid fields

### LINKED ISSUE #59: Allow access to express request response (req/res) objects?
I have some auth middleware which sets an auth interface to the express request object.

I would like to be able to get access to the auth interface in my "Custom behavior", so I can do something like this:

```js
router.use(crud('/machines', {
    ...sequelizeCrud(Machine),
    getList: ({ filter, limit, offset, order, req, res }) => { 
        return Machine.findAndCountAll({
            limit,
            offset,
            order,
            where: {
                ...filter,
                userId: req.auth.getAuthenticatedUser().id,
            }
        })
    }
}));

### PR DESCRIPTION
**Pull request by urakozz**
Provides optional req/res from express.
Addresses issue when it's impossible to search by any `uuid` field in Postgres because of unchangable LIKE syntax`%term%`

Closes #59

### CODE REVIEW

**Comment by urakozz** [comment]
Hello @nicgirault ! I'm not sure why build was not triggered, but could you please review and give your feedback? It looks like a big change, but overall it's backward-compatible (I noticed that #68 introduces breaking changes). Also made search smarter, improved types and updated tests!

**Comment by nicgirault** [comment]
Thanks a lot for your work.

**Comment by nicgirault** [comment]
Oups, you did not follow the semantic release nomenclature so there is no new version that will be triggered. Can you re-open a PR with 2 commits that update twice the readme. commit names should follow the naming `feat: expose req/res in crud methods` + `feat: search is smarter when searching UUID`

**Comment by urakozz** [comment]
I see, give me a second

**Pull request merged**
